### ISSUE TITLE
Error when running on Ubuntu 18.04

### ISSUE THREAD

**Issue by kyletozer** [bluebird75/maildir2mbox#5]
I get the following when running python maildir2mbox --help:

File "maildir2mbox.py", line 30
    print(prefix, *args)
                  ^
SyntaxError: invalid syntax

**Comment by bluebird75** [comment]
That's strange.
Can you copy the output of : 
 
    python --version

How did you install maildir2mbox ?

Can you also show me the full command-line which you are using ?

**Comment by kyletozer** [comment]
Worked after I installed python 3.7, sorry to waste your time. This script saved my life by the way, thanks!

**Comment by bluebird75** [comment]
Cool. I am happy that it was useful to you.
